[build]
builder = "NIXPACKS"
buildCommand = "cd SESSIONS-main && npm install"

[deploy]
startCommand = "cd SESSIONS-main && node index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
